version: '3'
services:
  myapp:
    build:
      context: .  # Build context is the current directory
      dockerfile: Dockerfile-notification  # Use the Dockerfile named "Dockerfile-Notification"
    volumes:
      - /archive/logs:/app/logs  # Mount logs
      - /archive/cred:/app/cred  # env and other credentials
      - /archive/data:/app/data # operation database location
      - /archive/config:/app/config # configiguration file
    #environment:
    #  - GOOGLE_APPLICATION_CREDENTIALS=/app/cred/service-account-key.json  # Add environment variables if needed
